version: '3'
services:
    publisher:
        image: 'node:8'
        volumes:
            - ./publisher.js:/usr/src/app/publisher.js
            - ./package.json:/usr/src/app/package.json
            - ./entrypoint.sh:/opt/entrypoint.sh
            - ./oracle:/opt/oracle
            - /usr/src/app/node_modules
        entrypoint:
            - /opt/entrypoint.sh
        environment:
            - TURN_USERNAME
            - TURN_CREDENTIAL
            - DEBUG=growbit-publisher
