version: '3'
services:
    subscriber:
        image: 'node:8'
        volumes:
            - ./subscribe.js:/usr/src/app/subscribe.js
            - ./package.json:/usr/src/app/package.json
            - ./yarn.lock:/usr/src/app/yarn.lock
            - ./entrypoint-subscribe.sh:/opt/entrypoint.sh
            - /usr/src/app/node_modules
        entrypoint:
            - /opt/entrypoint.sh
        environment:
            - TURN_USERNAME
            - TURN_CREDENTIAL
            - PUB_KEY
            - DEBUG
    publisher:
        image: 'node:8'
        volumes:
            - ./publish.js:/usr/src/app/publish.js
            - ./package.json:/usr/src/app/package.json
            - ./yarn.lock:/usr/src/app/yarn.lock
            - ./entrypoint-publish.sh:/opt/entrypoint.sh
            - /usr/src/app/node_modules
        entrypoint:
            - /opt/entrypoint.sh
        environment:
            - TURN_USERNAME
            - TURN_CREDENTIAL
            - DEBUG
